// for (let count=1; count<=5; count++)
// {
//     console.log("*")
// }

// calculate sum of 1 to 100
// let sum = 0;
// let n = 100;
// for (let i = 0; i <= n; i++) {
//     sum = sum + i;
// }
//     console.log("sum = ", sum);

// while loop
// let i= 1;
// while(i<=5) {

//     console.log("i=",i);
//       i++;
//         console.log("i=",i);
// } 

// do while loop
// let i = 3;
// do {
//     console.log("pluck");
//     i++;
// }
// while (i<8);

//  for of loop 
// let str = "PLUCK"
// let size = 0;
// for(let i of str) {
//     console.log("i=",i);
//     size++;
// }
// console.log("string size= ", size);

// for in loop
// let student = {
//     name : "palak",
//     age: 20,
//     cgpa: 9.5,
//     ispass: true
// };
// for(let i in student) {
//     console.log("i=",i, "value=", student[i]);
// }

// practice
// to print even no 1-100

// for ( let n=0; n<=100;n++){
//     if (n%2!==0){
//         console.log("n =",n);
//     }
// }

// practice 2 
// to create a game of random no guess

let gameNum = 23;

let userNum = prompt("Guess the Game Number");

while (userNum !== gs) {
    
}
console.log(userNum);
